from __future__ import annotations

import pathlib
import shutil
import string
import sys
import tempfile

import tomlkit

from ._input import (
    TemplateConfig,
    ask_specific_input,
    assert_input_valid,
    confirm_input,
    parse_args,
    read_input,
    resolve_changelog_url,
    resolve_docs_url,
    resolve_git_url,
)

TEMPLATE_DIR = pathlib.Path(__file__).parent.parent / "templates"


def main(argv: list[str] | None = None) -> None:
    # make welcome screen, CTRL+C to exit
    argv = argv or sys.argv[1:]

    config = parse_args(argv)

    if not config.no_confirm:
        try:
            config = read_input(config)

            if not confirm_input(config):
                config = ask_specific_input(config)
        except KeyboardInterrupt:
            print("\nRead CTRL+C")
            return
    else:
        try:
            assert_input_valid(config)
        except AssertionError as e:
            print(e)

    pkginit(config)

    print(config)


def pkginit(config: TemplateConfig) -> None:
    """
    Make a temporary directory and copy the template files to it.

    Then make the necessary edits to the files, and copy the whole directory
    to config.package_dir
    """
    tmp_file = tempfile.TemporaryDirectory()
    tmp_dir = pathlib.Path(tmp_file.name)
    dest_dir = config.package_dir

    # Copy the template files to the temporary directory
    files_to_copy = [
        "pyproject.toml",
        ".gitignore",
    ]
    for file_ in files_to_copy:
        shutil.copy(TEMPLATE_DIR / file_, tmp_dir / file_)

    shutil.copytree(TEMPLATE_DIR / "package_name", tmp_dir / "package_name")

    (tmp_dir / "package_name").rename(tmp_dir / config.package_module)
    _edit_gitignore(tmp_dir / ".gitignore", config.package_module)
    _make_readme(tmp_dir / "README.md", config)
    _edit_pyproject(tmp_dir / "pyproject.toml", config)

    shutil.rmtree(dest_dir, ignore_errors=True)
    shutil.copytree(tmp_dir, dest_dir)
    # tmp_file.cleanup()


def _edit_gitignore(gitignore_path: pathlib.Path, package_module: str) -> None:
    print("Hooking you up with a cool .gitignore...")
    with open(gitignore_path, "r") as f:
        lines = f.readlines()

    for i, line in enumerate(list(lines)):
        if line.startswith("package_name"):
            lines[i] = line.replace("package_name", package_module)

    with open(gitignore_path, "w") as f:
        f.write("".join(lines))


def _make_readme(
    readme_path: pathlib.Path,
    package_name: str | TemplateConfig,
    package_description: str | None = None,
    docs_url: str | None = None,
) -> None:
    print("Making README.md...")
    if isinstance(package_name, TemplateConfig):
        package_name_s = package_name.package_name
        package_description = package_name.package_description
        if package_name.package_url != "bare" and package_name.use_docs:
            docs_url = resolve_docs_url(package_name)
    else:
        package_name_s = package_name

    with open(readme_path, "w") as f:
        f.write(f"# {package_name_s}\n\n")
        if package_description:
            f.write(f"{package_description}\n\n")
        f.write("This is a package generated by dsb-devtools\n")
        f.write(
            "To get started, run "
            "`pip install -e . --config-settings editable_mode=compat`"
        )

        if docs_url:
            f.write(
                f"\n\nDocumentation available at [Acc-Py docserver]({docs_url})"
            )


def _edit_pyproject(
    pyproject_path: pathlib.Path, config: TemplateConfig
) -> None:
    print("Editing pyproject.toml")
    with open(pyproject_path, "r") as f:
        toml = tomlkit.loads(f.read())

    toml["project"]["name"] = config.package_name  # type: ignore[index]
    toml["project"]["description"] = config.package_description  # type: ignore[index]
    toml["project"]["authors"][0]["name"] = config.author_name  # type: ignore[index]
    toml["project"]["authors"][0]["email"] = config.author_email  # type: ignore[index]

    if config.package_url != "bare":
        toml["project"]["urls"]["homepage"] = config.package_url  # type: ignore[index]
        toml["project"]["urls"]["repository"] = resolve_git_url(  # type: ignore[index]
            config
        )
        toml["project"]["urls"]["changelog"] = resolve_changelog_url(config)  # type: ignore[index]
        toml["project"]["urls"]["documentation"] = resolve_docs_url(  # type: ignore[index]
            config
        )

    toml["tool"]["setuptools_scm"][  # type: ignore[index]
        "write_to"
    ] = f"{config.package_module}/__init__.py"  # noqa: E501

    toml["tool"]["setuptools"]["packages"]["find"]["include"] = [  # type: ignore[index]
        f"{config.package_module}*",
    ]
    del toml["tool"]["setuptools"]["package-data"]["package_name"]  # type: ignore[index,union-attr]
    toml["tool"]["setuptools"]["package-data"][config.package_module] = [  # type: ignore[index]
        "py.typed",
    ]

    with open(pyproject_path, "w") as f:
        f.write(tomlkit.dumps(toml))
