from __future__ import annotations
import typing
import pathlib
import shutil
import sys
import tempfile
import subprocess
import ruamel.yaml
import os

import tomlkit

from ._input import (
    TemplateConfig,
    ask_specific_input,
    assert_input_valid,
    confirm_input,
    parse_args,
    read_input,
    resolve_changelog_url,
    resolve_docs_url,
    resolve_git_url,
)

TEMPLATE_DIR = pathlib.Path(__file__).parent.parent / "templates"


def main(argv: list[str] | None = None) -> None:
    # make welcome screen, CTRL+C to exit
    argv = argv or sys.argv[1:]

    config = parse_args(argv)

    if not config.no_confirm:
        try:
            config = read_input(config)

            if not confirm_input(config):
                config = ask_specific_input(config)
        except KeyboardInterrupt:
            print("\nRead CTRL+C")
            return
    else:
        try:
            assert_input_valid(config)
        except AssertionError as e:
            print(e)

    pkginit(config)

    print(config)


def pkginit(config: TemplateConfig) -> None:
    """
    Make a temporary directory and copy the template files to it.

    Then make the necessary edits to the files, and copy the whole directory
    to config.package_dir
    """
    tmp_file = tempfile.TemporaryDirectory()
    tmp_dir = pathlib.Path(tmp_file.name)
    dest_dir = config.package_dir

    # Copy the template files to the temporary directory
    files_to_copy = [
        "pyproject.toml",
        ".gitignore",
    ]
    for file_ in files_to_copy:
        shutil.copy(TEMPLATE_DIR / file_, tmp_dir / file_)

    shutil.copytree(TEMPLATE_DIR / "package_name", tmp_dir / "package_name")

    (tmp_dir / "package_name").rename(tmp_dir / config.package_module)
    _edit_gitignore(tmp_dir / ".gitignore", config.package_module)
    _make_readme(tmp_dir / "README.md", config)
    _edit_pyproject(tmp_dir / "pyproject.toml", config)

    if config.use_docs:
        shutil.copytree(TEMPLATE_DIR / "docs", tmp_dir / "docs")
        _edit_docs(
            tmp_dir / "docs", config.package_name, config.package_module
        )

    if config.use_tests:
        shutil.copytree(TEMPLATE_DIR / "tests", tmp_dir / "tests")

    if config.use_precommit:
        shutil.copy(
            TEMPLATE_DIR / ".pre-commit-config.yaml",
            tmp_dir / ".pre-commit-config.yaml",
        )

    if config.use_ci:
        shutil.copy(
            TEMPLATE_DIR / ".gitlab-ci.yml",
            tmp_dir / ".gitlab-ci.yml",
        )
        _edit_gitlab_ci(tmp_dir / ".gitlab-ci.yml", config)

    # set up git and pre-commit
    if config.package_url != "bare":
        try:
            _setup_vcs(tmp_dir, config.package_url)
        except RuntimeError as e:
            print(
                "Failed to setup git repository. "
                "Please run `git init` in the repository directory"
                "to initialize the repository manually.\n"
                f"Error: {e}"
            )

    if config.use_precommit:
        try:
            _setup_precommit(tmp_dir)
        except RuntimeError as e:
            print(
                "Failed to setup pre-commit hooks. "
                "Please run `pre-commit install` in the repository directory"
                "to install the hooks manually.\n"
                f"Error: {e}"
            )

    shutil.rmtree(dest_dir, ignore_errors=True)
    shutil.copytree(tmp_dir, dest_dir)
    # tmp_file.cleanup()


def _edit_gitignore(gitignore_path: pathlib.Path, package_module: str) -> None:
    print("Hooking you up with a cool .gitignore...")
    _replace_in_file(gitignore_path, package_name=package_module)


def _make_readme(
    readme_path: pathlib.Path,
    package_name: str | TemplateConfig,
    package_description: str | None = None,
    docs_url: str | None = None,
) -> None:
    print("Making README.md...")
    if isinstance(package_name, TemplateConfig):
        package_name_s = package_name.package_name
        package_description = package_name.package_description
        if package_name.package_url != "bare" and package_name.use_docs:
            docs_url = resolve_docs_url(package_name)
    else:
        package_name_s = package_name

    with open(readme_path, "w") as f:
        f.write(f"# {package_name_s}\n\n")
        if package_description:
            f.write(f"{package_description}\n\n")
        f.write("This is a package generated by dsb-devtools\n")
        f.write(
            "To get started, run "
            "`pip install -e . --config-settings editable_mode=compat`"
        )

        if docs_url:
            f.write(
                f"\n\nDocumentation available at [Acc-Py docserver]({docs_url})"
            )


def _edit_pyproject(
    pyproject_path: pathlib.Path, config: TemplateConfig
) -> None:
    print("Editing pyproject.toml")
    with open(pyproject_path, "r") as f:
        toml = tomlkit.loads(f.read())

    toml["project"]["name"] = config.package_name  # type: ignore[index]
    toml["project"]["description"] = config.package_description  # type: ignore[index]
    toml["project"]["authors"][0]["name"] = config.author_name  # type: ignore[index]
    toml["project"]["authors"][0]["email"] = config.author_email  # type: ignore[index]

    if config.package_url != "bare":
        toml["project"]["urls"]["homepage"] = config.package_url  # type: ignore[index]
        toml["project"]["urls"]["repository"] = resolve_git_url(  # type: ignore[index]
            config
        )
        toml["project"]["urls"]["changelog"] = resolve_changelog_url(config)  # type: ignore[index]
        toml["project"]["urls"]["documentation"] = resolve_docs_url(  # type: ignore[index]
            config
        )

    toml["tool"]["setuptools_scm"][  # type: ignore[index]
        "write_to"
    ] = f"{config.package_module}/__init__.py"  # noqa: E501

    toml["tool"]["setuptools"]["packages"]["find"]["include"] = [  # type: ignore[index]
        f"{config.package_module}*",
    ]
    del toml["tool"]["setuptools"]["package-data"]["package_name"]  # type: ignore[index,union-attr]
    toml["tool"]["setuptools"]["package-data"][config.package_module] = [  # type: ignore[index]
        "py.typed",
    ]

    with open(pyproject_path, "w") as f:
        f.write(tomlkit.dumps(toml))


def _replace_in_file(
    file_path: pathlib.Path,
    replace: dict[str, str] | None = None,
    **kwargs: typing.Any,
) -> None:
    replace = replace or {}
    replace.update(kwargs)
    with open(file_path, "r") as f:
        lines = f.readlines()

    for i, line in enumerate(list(lines)):
        for old, new in replace.items():
            if old in line:
                lines[i] = line.replace(old, new)

    with open(file_path, "w") as f:
        f.writelines(lines)


def _edit_docs(
    docs_root: pathlib.Path, package_name: str, package_module: str
) -> None:
    print("Prettying up the docs...")
    docs_root = docs_root / "source"
    _replace_in_file(
        docs_root / "conf.py",
        {"package_name": package_module, "package-name": package_name},
    )
    _replace_in_file(
        docs_root / "api.rst",
        {"package_name": package_module, "package-name": package_name},
    )
    _replace_in_file(
        docs_root / "index.rst",
        {"package-name": package_name},
    )


def _edit_gitlab_ci(
    gitlab_ci_conf_path: pathlib.Path,
    config: TemplateConfig,
) -> None:
    print("Setting up CI pipeline")
    yaml = ruamel.yaml.YAML(typ="rt")
    with open(gitlab_ci_conf_path, "r") as f:
        ci_conf = yaml.load(f)

    ci_conf["variables"]["project_name"] = config.package_name

    if not config.use_docs:
        ci_conf.pop("._build_docs")
        ci_conf.pop("build_docs")
        ci_conf.pop("build_docs_on_tag")

    if not config.use_precommit:
        ci_conf.pop("pre-commit")

    if not config.use_tests:
        ci_conf.pop("test_dev")
        ci_conf.pop("test_wheel")

    if config.use_java:
        ci_conf["variables"][
            "ACC_PY_BASE_IMAGE_NAME"
        ] = "acc-py_cc7_openjdk11_ci"

        if config.use_tests:
            if "extends" in ci_conf["test_dev"]:
                ci_conf["test_dev"]["extends"].append(".acc_py_run_on_acc_py")
            else:
                ci_conf["test_dev"]["extends"] = [".acc_py_run_on_acc_py"]

    with open(gitlab_ci_conf_path, "w") as f:
        yaml.dump(ci_conf, f)


def _setup_vcs(repo_dir: pathlib.Path, repo_url: str) -> None:
    cwd = pathlib.Path.cwd()
    os.chdir(repo_dir)

    print("Setting up git repository...")

    try:
        command = ["git", "init"]

        output = subprocess.run(command, check=True, cwd=repo_dir)
        if output.returncode != 0:
            raise RuntimeError("Failed to initialize git repository")

        command = ["git", "remote", "add", "origin", repo_url]
        output = subprocess.run(command, check=True, cwd=repo_dir)
        if output.returncode != 0:
            raise RuntimeError("Failed to add remote origin")

        # checkout master branch and set it as default
        command = ["git", "branch", "-M", "master"]
        output = subprocess.run(command, check=True, cwd=repo_dir)
        if output.returncode != 0:
            raise RuntimeError("Failed to set master branch as default branch")
    except Exception as e:  # noqa: F722
        raise e
    finally:
        os.chdir(cwd)


def _setup_precommit(repo_dir: pathlib.Path) -> None:
    cwd = pathlib.Path().cwd()

    os.chdir(repo_dir)

    # check if pre-commit is installed
    try:
        command = ["pre-commit", "--version"]
        subprocess.run(command, check=True, cwd=repo_dir)
    except FileNotFoundError:
        print("pre-commit not found, installing...")
        command = ["pip", "install", "pre-commit"]
        output = subprocess.run(command, check=True, cwd=repo_dir)
        if output.returncode != 0:
            raise RuntimeError("Failed to install pre-commit")

    command = ["pre-commit", "install"]
    output = subprocess.run(command, check=True, cwd=repo_dir)
    if output.returncode != 0:
        raise RuntimeError("Failed to install pre-commit hooks")

    os.chdir(cwd)
